### ISSUE TITLE
Working on fix

### ISSUE THREAD

**Issue by mattbierner** [art-dot-git/80x40#171]
Glad people enjoyed the idea of this repo but I apologize for the scripts being so terrible.

Working on fixing the issues or at least recovering better from errors.

**Comment by mattbierner** [comment]
Several cases around merges should now be improved. Still not confident it will work 100% of the time but it should be better and produce more clear messages. 

Any outstanding pull request that got skipped/missed can be reprocess in their current state by closing and then reopening the pull request.

**Comment by nikrich** [comment]
Sorry just had to :)

**Comment by csu** [comment]
Is the script still running?

**Comment by mattbierner** [comment]
It should be. Is there a pull request that you opened/reopened within the last 4 or so days that is not merging correctly?

**Comment by csu** [comment]
No, I was just wondering why there are so many open PRs, but it looks like they all have conflicts or something wrong with them. Thanks!
