### ISSUE TITLE
shorter lines should be padded

### ISSUE THREAD

**Issue by neuhaus** [art-dot-git/80x40#236]
The commit failes if a line is shorter than 80 characters.
Why doesn't the merge script do the padding?

**Comment by mattbierner** [comment]
Yes, only blocks that are exactly 80x40 characters can be merged. The script currently does not trim white space or insert extra white space for padding.

Feel free to submit a PR if you would like to improve this.

**Comment by neuhaus** [comment]
I guess this issue belongs here: https://github.com/art-dot-git/80x40-client
