### ISSUE TITLE
Bot not merging, is it not running anymore?

### ISSUE THREAD

**Issue by evinism** [art-dot-git/80x40#238]
Is the bot down? Would love a quick message if this is decommissioned.

**Comment by mattbierner** [comment]
Yes, it looks like it did not pick up the PR you just submitted. I'll restart it when I get a chance, but that will be early next week.

Thanks for the report.

**Comment by mattbierner** [comment]
Accidentally started the bot with the wrong user at one point. Fixed permissions and merged in #237. Thanks.
